# Generated by Django 5.2.13 on 2026-04-08 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя игра', max_length=100)),
                ('size', models.PositiveIntegerField(default=16)),
                ('grid', models.JSONField()),
                ('generation', models.PositiveIntegerField(default=0)),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохранение игры',
                'verbose_name_plural': 'Сохранения игр',
                'ordering': ['-updated_at'],
            },
        ),
    ]
